title: Joby's Blog
description: Personal thoughts and writings
baseurl: "/blog"
url: "https://knowjoby.github.io"

theme: minima

author:
  name: Joby John

minima:
  skin: classic

show_excerpts: true

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

header_pages:
  - about.md
  - logs.md
